export const ADD_WORKOUT = 'ADD_WORKOUT'
export const WORKOUT_DATE_CHANGED = 'WORKOUT_DATE_CHANGED'
export const REMOVE_WORKOUT = 'REMOVE_WORKOUT'

export const EXERCISE_TITLE_CHANGED = 'EXERCISE_TITLE_CHANGED'
export const ADD_EXERCISE = 'ADD_EXERCISE'
export const REMOVE_EXERCISE = 'REMOVE_EXERCISE'

export const WEIGHT_CHANGED = 'WEIGHT_CHANGED'
export const REPETITIONS_CHANGED = 'REPETITIONS_CHANGED'
export const SAVE_NEW_SET = 'SAVE_NEW_SET'
export const SHOW_NEW_SET = 'SHOW_NEW_SET'
export const REMOVE_SET = 'REMOVE_SET'
